[2016-08-16 09:25:24,295] ERROR [play-thread-1] controllers.TaskExecutor.take(TaskExecutor.java:678) - 买手=maimai违规注册多个账号，本次使用买号=use不属于当前登录用户！
[2016-08-16 09:26:26,379] ERROR [jobs-thread-7] play.Logger.niceThrowable(Logger.java:604) - 

@714l9dg36
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskExecutor.java around line 81)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method perform(long) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method perform(long) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 09:33:50,633] ERROR [play-thread-1] controllers.TaskExecutor.take(TaskExecutor.java:755) - 买手=maimai违规注册多个账号，本次使用买号=use不属于当前登录用户！
[2016-08-16 09:37:11,873] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714l9dg38
Internal Server Error (500) for request GET /buyer/task/perform2/6475

Execution exception (In /app/models/BuyerTask2.java around line 1064)
NullPointerException occured : null

play.exceptions.JavaExecutionException
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException
	at models.BuyerTask2.findForPerforming(BuyerTask2.java:1064)
	at controllers.TaskExecutor.perform2(TaskExecutor.java:169)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
[2016-08-16 09:39:53,953] ERROR [play-thread-1] controllers.TaskExecutor.take(TaskExecutor.java:755) - 买手=maimai违规注册多个账号，本次使用买号=use不属于当前登录用户！
[2016-08-16 09:41:33,429] ERROR [play-thread-1] controllers.TaskExecutor.take(TaskExecutor.java:755) - 买手=maimai违规注册多个账号，本次使用买号=use不属于当前登录用户！
[2016-08-16 09:43:58,368] ERROR [play-thread-1] controllers.TaskExecutor.take(TaskExecutor.java:755) - 买手=maimai违规注册多个账号，本次使用买号=use不属于当前登录用户！
[2016-08-16 09:55:09,434] ERROR [jobs-thread-7] play.Logger.niceThrowable(Logger.java:604) - 

@714l9dg39
Error during job execution (jobs.TaskKeeper)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	... 1 more
[2016-08-16 09:58:46,367] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 09:58:46,367] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
java.lang.NullPointerException
	at controllers.TaskExecutor.take2(TaskExecutor.java:958)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 10:32:24,033] ERROR [jobs-thread-3] null - 

@714li4kgi
Error during job execution (jobs.AddKwdForFlow)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	... 1 more
[2016-08-16 10:37:04,260] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 10:37:04,260] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - The validated string is empty
java.lang.IllegalArgumentException: The validated string is empty
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:339)
	at controllers.TaskExecutor.isAvailableBuyerAccountAndItem(TaskExecutor.java:1210)
	at controllers.TaskExecutor.take2(TaskExecutor.java:1027)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 11:02:09,600] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:13:31,149] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 11:13:31,149] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at models.BuyerTask.findTodoTask(BuyerTask.java:1234)
	at controllers.TaskCenter.isTakeTasks(TaskCenter.java:449)
	at controllers.TaskCenter.listTasks(TaskCenter.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 11:13:33,650] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 11:13:33,650] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at models.BuyerTask.findTodoTask(BuyerTask.java:1234)
	at controllers.TaskCenter.isTakeTasks(TaskCenter.java:449)
	at controllers.TaskCenter.listTasks(TaskCenter.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 11:16:44,950] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:17:48,837] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:17:52,354] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:21:02,339] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:23:50,358] ERROR [jobs-thread-5]  - 

@714looa5d
Error during job execution (jobs.TaskKeeper)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	... 1 more
[2016-08-16 11:24:34,686] ERROR [play-thread-1]  - 

@714looa5f
Internal Server Error (500) for request GET /buyer/tasks2

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 11:24:35,574] ERROR [play-thread-1]  - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 11:24:39,243] ERROR [play-thread-1]  - 

@714looa5g
Internal Server Error (500) for request GET /buyer/tasks2

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 11:24:39,703] ERROR [play-thread-1]  - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 11:25:51,449] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:31:23,198] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 11:31:26,612] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 13:49:22,699] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714mi15jh
Internal Server Error (500) for request POST /doLogin

Execution exception (In /app/models/Task.java around line 876)
NullPointerException occured : Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)

play.exceptions.JavaExecutionException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at models.BuyerTask.findTodoTask(BuyerTask.java:1234)
	at controllers.UserAuthentication.setUserTodoTask(UserAuthentication.java:427)
	at controllers.UserAuthentication.doLogin(UserAuthentication.java:414)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
[2016-08-16 14:12:03,902] ERROR [jobs-thread-6] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hch
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskCenter.java around line 1477)
The file /app/controllers/TaskCenter.java could not be compiled. Error raised is : Duplicate method buyerTaskDetail(long) in type TaskCenter

play.exceptions.CompilationException: Duplicate method buyerTaskDetail(long) in type TaskCenter
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 14:23:10,516] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hcj
Internal Server Error (500) for request GET /buyer/task2/6487

Execution exception (In /app/models/BuyerTask2.java around line 1098)
PersistenceException occured :  ### Error querying database.  Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO ### The error may exist in models/mappers/BuyerTaskMapper2.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: select     bt.buyer_id,     bt.device,     t.platform,     bt.buyer_account_nick,     bt.paid_fee,     t.base_order_ingot,     t.extra_reward_ingot,     bt.experience,     bt.reward_ingot,     t.shop_name,     t.good_comment_words,     t.good_comment_img,     t.id taskId,     bt.id id,     bt.order_id,     bt.express_no,     bt.take_time,     bt.seller_id,     t.seller_nick,     t.sys_refund,     t.type taskType,     bt.status,     bt.trans_no,     bt.start_time,     bt.finish_time,     t.sys_express sysExpress,     t.express_type,     t.item_url,     t.item_title,     t.item_pic,     t.item_price,     t.item_buy_num,     t.is_free_shipping,     t.sys_refund,     t.task_request,     u.nick buyerNick   from     buyer_task bt      left join task2 t on t.id = bt.task_id     left join user u on u.id = bt.buyer_id   where bt.id = ?   limit 1 ### Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO

play.exceptions.JavaExecutionException: 
### Error querying database.  Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO
### The error may exist in models/mappers/BuyerTaskMapper2.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select     bt.buyer_id,     bt.device,     t.platform,     bt.buyer_account_nick,     bt.paid_fee,     t.base_order_ingot,     t.extra_reward_ingot,     bt.experience,     bt.reward_ingot,     t.shop_name,     t.good_comment_words,     t.good_comment_img,     t.id taskId,     bt.id id,     bt.order_id,     bt.express_no,     bt.take_time,     bt.seller_id,     t.seller_nick,     t.sys_refund,     t.type taskType,     bt.status,     bt.trans_no,     bt.start_time,     bt.finish_time,     t.sys_express sysExpress,     t.express_type,     t.item_url,     t.item_title,     t.item_pic,     t.item_price,     t.item_buy_num,     t.is_free_shipping,     t.sys_refund,     t.task_request,     u.nick buyerNick   from     buyer_task bt      left join task2 t on t.id = bt.task_id     left join user u on u.id = bt.buyer_id   where bt.id = ?   limit 1
### Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO
### The error may exist in models/mappers/BuyerTaskMapper2.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select     bt.buyer_id,     bt.device,     t.platform,     bt.buyer_account_nick,     bt.paid_fee,     t.base_order_ingot,     t.extra_reward_ingot,     bt.experience,     bt.reward_ingot,     t.shop_name,     t.good_comment_words,     t.good_comment_img,     t.id taskId,     bt.id id,     bt.order_id,     bt.express_no,     bt.take_time,     bt.seller_id,     t.seller_nick,     t.sys_refund,     t.type taskType,     bt.status,     bt.trans_no,     bt.start_time,     bt.finish_time,     t.sys_express sysExpress,     t.express_type,     t.item_url,     t.item_title,     t.item_pic,     t.item_price,     t.item_buy_num,     t.is_free_shipping,     t.sys_refund,     t.task_request,     u.nick buyerNick   from     buyer_task bt      left join task2 t on t.id = bt.task_id     left join user u on u.id = bt.buyer_id   where bt.id = ?   limit 1
### Cause: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy57.selectByIdForViewDetail(Unknown Source)
	at models.BuyerTask2.findDetail(BuyerTask2.java:1098)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1544)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
Caused by: java.lang.IllegalArgumentException: No enum const class enums.TaskType.TOUPIAO
	at java.lang.Enum.valueOf(Enum.java:196)
	at org.apache.ibatis.type.EnumTypeHandler.getNullableResult(EnumTypeHandler.java:47)
	at org.apache.ibatis.type.EnumTypeHandler.getNullableResult(EnumTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:55)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:413)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:336)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:291)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:266)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:236)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:150)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:60)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 13 more
[2016-08-16 14:30:24,967] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hck
Internal Server Error (500) for request GET /buyer/task2/6487

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 225)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform for class: vos.BuyerTaskVo2 Possible solutions: platform2.

play.exceptions.TemplateExecutionException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1587)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at /app/views/TaskCenter/buyerTaskDetail2.html.(line:225)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-08-16 14:31:20,210] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hcl
Internal Server Error (500) for request GET /buyer/task2/6487

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 225)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform for class: vos.BuyerTaskVo2 Possible solutions: platform2.

play.exceptions.TemplateExecutionException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1587)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at /app/views/TaskCenter/buyerTaskDetail2.html.(line:225)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-08-16 14:31:26,995] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hcm
Internal Server Error (500) for request GET /buyer/task2/6487

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 225)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform for class: vos.BuyerTaskVo2 Possible solutions: platform2.

play.exceptions.TemplateExecutionException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1587)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at /app/views/TaskCenter/buyerTaskDetail2.html.(line:225)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-08-16 14:33:38,704] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hcn
Internal Server Error (500) for request GET /buyer/tasks2

Template execution error (In /app/views/nui.html around line null)
Execution error occured in template /app/views/nui.html. Exception raised was OutOfMemoryError : PermGen space.

play.exceptions.TemplateExecutionException: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTasks2(TaskCenter.java:1022)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
[2016-08-16 14:33:38,704] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hco
Error during the 500 response generation

Template execution error (In /app/views/errors/500.html around line 11)
Execution error occured in template /app/views/errors/500.html. Exception raised was OutOfMemoryError : PermGen space.

play.exceptions.TemplateExecutionException: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.server.PlayHandler.serve500(PlayHandler.java:792)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.templates.GroovyTemplate$TClassLoader.defineTemplate(GroovyTemplate.java:79)
	at play.templates.GroovyTemplate.directLoad(GroovyTemplate.java:92)
	at play.templates.BaseTemplate.loadFromCache(BaseTemplate.java:56)
	at play.templates.TemplateLoader.load(TemplateLoader.java:81)
	at play.templates.TemplateLoader.load(TemplateLoader.java:179)
	at play.templates.GroovyTemplate$ExecutableTemplate.invokeTag(GroovyTemplate.java:383)
[2016-08-16 14:34:41,348] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hcp
Internal Server Error (500) for request GET /buyer/tasks2

Template execution error (In /app/views/nui.html around line 20)
Execution error occured in template /app/views/nui.html. Exception raised was OutOfMemoryError : PermGen space.

play.exceptions.TemplateExecutionException: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:295)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTasks2(TaskCenter.java:1022)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2300)
	at java.lang.Class.getDeclaredFields(Class.java:1745)
	at java.security.AccessController.doPrivileged(Native Method)
	at /app/views/nui.html.(line:20)
[2016-08-16 14:34:41,768] ERROR [play-thread-1] play.Logger.error(Logger.java:457) - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:16,260] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hd0
Internal Server Error (500) for request GET /buyer/tasks2

Execution exception (In /app/controllers/TaskCenter.java around line 1022)
RuntimeException occured : java.lang.OutOfMemoryError: PermGen space

play.exceptions.JavaExecutionException: java.lang.OutOfMemoryError: PermGen space
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:93)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTasks2(TaskCenter.java:1022)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:16,260] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hd1
Error during the 500 response generation

Template execution error (In /app/views/errors/500.html around line 11)
Execution error occured in template /app/views/errors/500.html. Exception raised was RuntimeException : java.lang.OutOfMemoryError: PermGen space.

play.exceptions.TemplateExecutionException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.server.PlayHandler.serve500(PlayHandler.java:792)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:93)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.GroovyTemplate$ExecutableTemplate.invokeTag(GroovyTemplate.java:414)
	at /app/views/errors/500.html.(line:11)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 4 more
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:20,817] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hd2
Internal Server Error (500) for request GET /buyer/tasks2

Execution exception (In /app/controllers/TaskCenter.java around line 1022)
RuntimeException occured : java.lang.OutOfMemoryError: PermGen space

play.exceptions.JavaExecutionException: java.lang.OutOfMemoryError: PermGen space
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:93)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTasks2(TaskCenter.java:1022)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:20,827] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - Error during the 500 response generation
java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:93)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.server.PlayHandler.serve500(PlayHandler.java:792)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:40,377] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hd3
Internal Server Error (500) for request GET /tasks2

Execution exception
InvocationTargetException occured : null

play.exceptions.JavaExecutionException
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:230)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.reflect.InvocationTargetException
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:35:40,377] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - Error during the 500 response generation
java.lang.RuntimeException: java.lang.OutOfMemoryError: PermGen space
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:93)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.server.PlayHandler.serve500(PlayHandler.java:792)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:36:29,768] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714ml0hd4
Internal Server Error (500) for request GET /tasks2

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.Invoker$Invocation.run(Invoker.java:305)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:36:29,768] ERROR [play-thread-1] play.Logger.error(Logger.java:457) - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 14:37:29,685] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bp2
Internal Server Error (500) for request GET /buyer/task2/6487

Template execution error (In /app/views/TaskCenter/buyerTaskDetail2.html around line 287)
Execution error occured in template /app/views/TaskCenter/buyerTaskDetail2.html. Exception raised was MissingPropertyException : No such property: platform for class: vos.BuyerTaskVo2 Possible solutions: platform2.

play.exceptions.TemplateExecutionException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at play.templates.BaseTemplate.throwException(BaseTemplate.java:86)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:285)
	at play.templates.Template.render(Template.java:26)
	at play.templates.GroovyTemplate.render(GroovyTemplate.java:208)
	at play.mvc.results.RenderTemplate.<init>(RenderTemplate.java:24)
	at play.mvc.Controller.renderTemplate(Controller.java:676)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskCenter.buyerTaskDetail2(TaskCenter.java:1587)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
Caused by: groovy.lang.MissingPropertyException: No such property: platform for class: vos.BuyerTaskVo2
Possible solutions: platform2
	at /app/views/TaskCenter/buyerTaskDetail2.html.(line:287)
	at play.templates.GroovyTemplate.internalRender(GroovyTemplate.java:260)
	... 13 more
[2016-08-16 14:47:19,241] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bp3
Error during job execution (jobs.AddKwdForFlow)

Compilation error (In /app/controllers/TaskExecutor.java around line 694)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method cancelBuyerTask(long) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method cancelBuyerTask(long) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 14:47:22,192] ERROR [jobs-thread-6] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bp5
Error during job execution (jobs.BuyerTaskCancel)

Compilation error (In /app/controllers/TaskExecutor.java around line 694)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method cancelBuyerTask(long) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method cancelBuyerTask(long) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 14:47:22,283] ERROR [jobs-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bp7
Error during job execution (jobs.GetExpressNo)

Compilation error (In /app/controllers/TaskExecutor.java around line 694)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method cancelBuyerTask(long) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method cancelBuyerTask(long) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 14:47:22,743] ERROR [jobs-thread-3] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bp9
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskExecutor.java around line 694)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method cancelBuyerTask(long) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method cancelBuyerTask(long) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 14:56:15,610] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:56:19,358] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:56:22,137] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:56:50,119] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:56:57,764] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:57:42,182] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:57:45,632] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-08-16 14:59:17,518] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bpb
Internal Server Error (500) for request GET /buyer/task/perform/6489

Execution exception (In /app/models/Task.java around line 876)
NullPointerException occured : Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)

play.exceptions.JavaExecutionException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at controllers.TaskExecutor.perform(TaskExecutor.java:92)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	... 1 more
[2016-08-16 14:59:35,695] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 14:59:35,695] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
java.lang.NullPointerException: Try to read platform on null object models.Task (models.Task.isTaoBaoAndTmall, line 876)
	at play.classloading.enhancers.PropertiesEnhancer$FieldAccessor.invokeReadProperty(PropertiesEnhancer.java:214)
	at models.Task.isTaoBaoAndTmall(Task.java:876)
	at models.BuyerTask.findTodoTask(BuyerTask.java:1234)
	at controllers.TaskCenter.isTakeTasks(TaskCenter.java:451)
	at controllers.TaskCenter.listTasks(TaskCenter.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 15:11:05,001] ERROR [jobs-thread-4] play.Logger.niceThrowable(Logger.java:604) - 

@714mo9bpc
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/domain/TaskStats2.java around line 71)
The file /app/domain/TaskStats2.java could not be compiled. Error raised is : Type mismatch: cannot convert from BuyerTaskMapper2 to BuyerTaskMapper

play.exceptions.CompilationException: Type mismatch: cannot convert from BuyerTaskMapper2 to BuyerTaskMapper
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 15:26:09,251] ERROR [jobs-thread-1]  - 

@714mo9bpe
Error during job execution (jobs.TaskKeeper)

Oops: OutOfMemoryError
An unexpected error occured caused by exception OutOfMemoryError: PermGen space

play.exceptions.UnexpectedException: Unexpected Error
	at play.Invoker$Invocation.onException(Invoker.java:245)
	at play.jobs.Job.onException(Job.java:154)
	at com.aton.job.BaseJob.onException(BaseJob.java:49)
	at play.jobs.Job.call(Job.java:224)
	at Invocation.Job(Play!)
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at play.classloading.ApplicationClassloader.loadApplicationClass(ApplicationClassloader.java:152)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:433)
	at play.Play.start(Play.java:527)
	at play.Play.detectChanges(Play.java:653)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	... 1 more
[2016-08-16 15:49:48,229] ERROR [play-thread-1]  - Oops. Error in Logger !
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 15:52:25,688] ERROR [play-thread-1]  - Error during the 500 response generation
java.lang.OutOfMemoryError: PermGen space
[2016-08-16 16:00:50,332] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 16:00:50,332] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy46.selectForCheckTaking(Unknown Source)
	at models.BuyerTask2._checkBuyerTaskExist(BuyerTask2.java:331)
	at models.BuyerTask2.isDuplicateTaking(BuyerTask2.java:322)
	at controllers.TaskCenter.isTakeTasks2(TaskCenter.java:601)
	at controllers.TaskCenter.listTasks2(TaskCenter.java:394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 35 more
[2016-08-16 16:01:31,155] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 16:01:31,155] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy46.selectForCheckTaking(Unknown Source)
	at models.BuyerTask2._checkBuyerTaskExist(BuyerTask2.java:331)
	at models.BuyerTask2.isDuplicateTaking(BuyerTask2.java:322)
	at controllers.TaskCenter.isTakeTasks2(TaskCenter.java:601)
	at controllers.TaskCenter.listTasks2(TaskCenter.java:394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 35 more
[2016-08-16 16:01:33,418] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 16:01:33,418] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
### The error may exist in models/mappers/BuyerTaskMapper2.java (best guess)
### The error may involve models.mappers.BuyerTaskMapper2.selectForCheckTaking-Inline
### The error occurred while setting parameters
### SQL: select id from buyer_task2 where buyer_account_id = ?  and task_id =? and status != ? limit 1
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy46.selectForCheckTaking(Unknown Source)
	at models.BuyerTask2._checkBuyerTaskExist(BuyerTask2.java:331)
	at models.BuyerTask2.isDuplicateTaking(BuyerTask2.java:322)
	at controllers.TaskCenter.isTakeTasks2(TaskCenter.java:601)
	at controllers.TaskCenter.listTasks2(TaskCenter.java:394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'waguke.buyer_task2' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:1392)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	... 35 more
[2016-08-16 16:34:23,942] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 16:34:23,942] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - The validated string is empty
java.lang.IllegalArgumentException: The validated string is empty
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:339)
	at controllers.TaskExecutor.isAvailableBuyerAccountAndItem(TaskExecutor.java:1261)
	at controllers.TaskExecutor.take2(TaskExecutor.java:1072)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 16:39:00,189] ERROR [jobs-thread-7] play.Logger.niceThrowable(Logger.java:604) - 

@714ne878i
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskExecutor.java around line 1254)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method isAvailableBuyerAccountAndItem(long, String) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method isAvailableBuyerAccountAndItem(long, String) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 16:39:00,300] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@714ne878k
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/TaskExecutor.java around line 1254)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method isAvailableBuyerAccountAndItem(long, String) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method isAvailableBuyerAccountAndItem(long, String) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 16:47:03,951] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:232) - =======>Server Fatal Error<======
[2016-08-16 16:47:03,951] ERROR [play-thread-1] com.aton.base.BaseController.handleServerError(BaseController.java:233) - The validated string is empty
java.lang.IllegalArgumentException: The validated string is empty
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321)
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:339)
	at controllers.TaskExecutor.isAvailableBuyerAccountAndItem2(TaskExecutor.java:1272)
	at controllers.TaskExecutor.take2(TaskExecutor.java:1072)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
[2016-08-16 17:10:15,488] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@714niapbf
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskPublish.java around line 507)
The file /app/controllers/TaskPublish.java could not be compiled. Error raised is : Duplicate local variable shop

play.exceptions.CompilationException: Duplicate local variable shop
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 17:10:15,579] ERROR [jobs-thread-2] play.Logger.niceThrowable(Logger.java:604) - 

@714niapbh
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/TaskPublish.java around line 507)
The file /app/controllers/TaskPublish.java could not be compiled. Error raised is : Duplicate local variable shop

play.exceptions.CompilationException: Duplicate local variable shop
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-08-16 17:14:48,493] ERROR [play-thread-1] models.Task2.save(Task2.java:424) - 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:177)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:169)
	at models.Task2.save(Task2.java:422)
	at controllers.TaskPublish.saveTask2(TaskPublish.java:511)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:127)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:114)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:109)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:201)
	at org.apache.ibatis.executor.CachingExecutor.commit(CachingExecutor.java:104)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:174)
	... 29 more
Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2465)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:85)
	at com.sun.proxy.$Proxy20.executeBatch(Unknown Source)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:103)
	... 34 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'item_id' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1777)
	... 43 more
[2016-08-16 17:28:34,915] ERROR [play-thread-1] models.Task2.save(Task2.java:432) - 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:177)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:169)
	at models.Task2.save(Task2.java:430)
	at controllers.TaskPublish.saveTask2(TaskPublish.java:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:267)
	at play.Invoker$Invocation$1.apply(Invoker.java:290)
	at play.Invoker$Invocation$1.apply(Invoker.java:287)
	at play.db.jpa.JPA.withTransaction(JPA.java:258)
	at play.db.jpa.JPA.withinFilter(JPA.java:217)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:299)
	at play.Invoker$Invocation.withinFilter(Invoker.java:271)
	at play.Invoker$Invocation.run(Invoker.java:287)
	at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:245)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.ibatis.executor.BatchExecutorException: models.mappers.TaskMapper2.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:127)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:114)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:109)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:201)
	at org.apache.ibatis.executor.CachingExecutor.commit(CachingExecutor.java:104)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:174)
	... 29 more
Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'item_id' at row 1
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:2465)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:85)
	at com.sun.proxy.$Proxy20.executeBatch(Unknown Source)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:103)
	... 34 more
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'item_id' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1777)
	... 43 more
[2016-09-05 13:52:08,515] ERROR [main] play.Logger.error(Logger.java:426) - Could not bind on port 80
[2016-09-05 14:10:09,083] ERROR [play-thread-1] com.aton.base.secure.Secure.checkAuthentication(Secure.java:92) - Login admin not exists,admin_id=null
[2016-09-05 14:14:16,723] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:14:16,772] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:21:15,472] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:23:39,833] ERROR [play-thread-1] play.Logger.niceThrowable(Logger.java:604) - 

@71ac7o3n0
Internal Server Error (500) for request GET /buyer/task/confirmGoods2/WEIXIN

Template not found (In /app/controllers/TaskExecutor.java around line 740)
The template TaskExecutor/confirmRecv2.html does not exist.

play.exceptions.TemplateNotFoundException: Template not found : TaskExecutor/confirmRecv2.html
	at play.mvc.Controller.renderTemplate(Controller.java:685)
	at play.mvc.Controller.renderTemplate(Controller.java:656)
	at play.mvc.Controller.render(Controller.java:713)
	at controllers.TaskExecutor.confirmRecv2(TaskExecutor.java:740)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
	at Invocation.HTTP Request(Play!)
[2016-09-05 14:27:26,188] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:27:26,237] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:27:49,814] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:27:49,871] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:27:53,696] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:27:53,753] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:30:34,728] ERROR [jobs-thread-5] play.Logger.niceThrowable(Logger.java:604) - 

@71ac7o3n1
Error during job execution (jobs.TaskKeeper)

Compilation error (In /app/controllers/TaskExecutor.java around line 756)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method confirmRecvGoods(long, BuyerTaskStepVo) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method confirmRecvGoods(long, BuyerTaskStepVo) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-05 14:30:34,847] ERROR [jobs-thread-8] play.Logger.niceThrowable(Logger.java:604) - 

@71ac7o3n3
Error during job execution (jobs.TaskKeeper2)

Compilation error (In /app/controllers/TaskExecutor.java around line 756)
The file /app/controllers/TaskExecutor.java could not be compiled. Error raised is : Duplicate method confirmRecvGoods(long, BuyerTaskStepVo) in type TaskExecutor

play.exceptions.CompilationException: Duplicate method confirmRecvGoods(long, BuyerTaskStepVo) in type TaskExecutor
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:256)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:480)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:292)
	at play.classloading.ApplicationClasses$ApplicationClass.compile(ApplicationClasses.java:289)
	at play.classloading.ApplicationClassloader.detectChanges(ApplicationClassloader.java:326)
	at play.Play.detectChanges(Play.java:636)
	at play.Invoker$Invocation.init(Invoker.java:199)
	at play.jobs.Job.call(Job.java:185)
	at Invocation.Job(Play!)
[2016-09-05 14:33:54,171] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:33:54,226] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:37:26,884] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
[2016-09-05 14:37:26,962] ERROR [play-thread-1] com.aton.base.BaseController.handleWrongInput(BaseController.java:291) - Input wrong: Incorrect value
